### ISSUE TITLE
preranked returns error when called from run_gsea with pe="label"

### ISSUE THREAD

**Issue by ACastanza** [KwatME/gsea#6]
```
Traceback (most recent call last):
  File "/opt/gpbeta_2/gp_home/taskLib/GSEA2.1.2063/run.gsea2.py", line 52, in <module>
    main()
  File "/opt/gpbeta_2/gp_home/taskLib/GSEA2.1.2063/run.gsea2.py", line 31, in main
    nu_se_st = run_gsea(
  File "/usr/local/lib/python3.8/site-packages/gsea/run_gsea.py", line 30, in run_gsea
    return run_prerank_gsea(ge_sc, gm, **ke)
TypeError: run_prerank_gsea() got an unexpected keyword argument 'pe'
```

Looking at the updated commands in the example notebook, did you remove a bunch of the parameters that we kind of need?

**Comment by KwatME** [comment]
The function call in the notebook uses only the required positional arguments. If you type tab, then Jupiter should show you all the keyword arguments.

Because the prerank permutes only by gene set (what you mentioned in the meeting), I removed the option to specify pe, which is permutation type.

**Comment by ACastanza** [comment]
**I'm not running preranked**, I'm running standard gsea with the run_gsea command and yet it is for some reason returning an error about preranked which is not what I ran.

I'm not running this in jupyter so please put back all the possible parameters and options in the documentation.

**Comment by KwatME** [comment]
Fixed the pe bug. Added documentation of all parameters in the README.md.

**Comment by ACastanza** [comment]
Reopening this issue, the error has changed slightly but is still occurring

```
Traceback (most recent call last):
  File "/opt/gpbeta_2/gp_home/taskLib/GSEA2.1.2063/run.gsea2.py", line 52, in <module>
    main()
  File "/opt/gpbeta_2/gp_home/taskLib/GSEA2.1.2063/run.gsea2.py", line 31, in main
    nu_se_st = run_gsea(
  File "/usr/local/lib/python3.8/site-packages/gsea/run_gsea.py", line 30, in run_gsea
    return run_prerank_gsea(ge_sc, se_ge_, **ke)
TypeError: run_prerank_gsea() got an unexpected keyword argument 'pe'
:

```

**Comment by KwatME** [comment]
I tried to run with and without pe and both worked.

![Screen Shot 2021-07-22 at 14 03 54](https://user-images.githubusercontent.com/7741548/126702681-fe550780-0486-471c-be01-40b0005428eb.png)
![Screen Shot 2021-07-22 at 14 03 48](https://user-images.githubusercontent.com/7741548/126702686-50e0d35d-881b-4eff-b829-4ab7b68956cb.png)
I suspect that the problem is not updating the version number in setup.py so when you tried to install the updated version, the update did not work. Can you try again?

**Comment by KwatME** [comment]
I ran the code in GSEA2 repo. I was able to run it.

![Screen Shot 2021-07-22 at 14 10 03](https://user-images.githubusercontent.com/7741548/126703262-5a9e271c-2575-40ea-b4c3-d5e2b7940673.png)

**Comment by ACastanza** [comment]
The container is rebuilding now, I'll let you know how it goes once its done

**Comment by KwatME** [comment]
Ok

**Comment by ACastanza** [comment]
Still returning the identical error. Looking at the docker build that completed, it looks like it isn't recognizing that there is anything changed in the repo and is stuck on cached versions even when I force a build.

**Comment by KwatME** [comment]
I see. Hope you can get it fixed. Perhaps print out the versions of the main tools.

**Comment by ACastanza** [comment]
Forcing a complete rebuild worked
